#!/usr/bin/env node
/**
 * Creates agents under YOUR Toolhouse account, deploys them, and creates app/.env.
 * Run: npm run setup:env
 *
 * This script uses `th new` to create agents in your account (generating IDs tied to you),
 * then deploys them and captures the URLs for app/.env.
 *
 * Requires: TOOLHOUSE_API_KEY in ~/.toolhouse or env (run `npx th login` if needed)
 */

const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

const PROJECT_ROOT = path.join(__dirname, '..')
const APP_DIR = path.join(PROJECT_ROOT, 'app')
const ENV_PATH = path.join(APP_DIR, '.env')
const ENV_EXAMPLE_PATH = path.join(APP_DIR, '.env.example')

const AGENTS = [
  { template: 'orchestrator.template.yaml', output: 'orchestrator.yaml', temp: '_setup_temp_orchestrator.yaml' },
  { template: 'debater.template.yaml', output: 'debater.yaml', temp: '_setup_temp_debater.yaml' },
  { template: 'synthesizer.template.yaml', output: 'synthesizer.yaml', temp: '_setup_temp_synthesizer.yaml' },
]
const URL_REGEX = /https:\/\/agents\.toolhouse\.ai\/[a-zA-Z0-9-]+/g
const ID_REGEX = /id:\s*([a-f0-9-]{36})/i

function createAgentAndDeploy({ template, output, temp }) {
  const templatePath = path.join(PROJECT_ROOT, template)
  const outputPath = path.join(PROJECT_ROOT, output)
  const tempPath = path.join(PROJECT_ROOT, temp)

  console.log(`Creating ${output}...`)

  // 1. Run th new with temp file to create agent under user's account
  execSync(`npx th new ${temp}`, {
    encoding: 'utf8',
    cwd: PROJECT_ROOT,
    stdio: ['pipe', 'pipe', 'pipe'],
  })

  // 2. Extract id from the temp file
  const tempContent = fs.readFileSync(tempPath, 'utf8')
  const idMatch = tempContent.match(ID_REGEX)
  if (!idMatch) {
    fs.unlinkSync(tempPath)
    throw new Error(`Could not parse agent ID from ${temp}`)
  }
  const agentId = idMatch[1]

  // 3. Read template, inject id, write output
  const templateContent = fs.readFileSync(templatePath, 'utf8')
  const finalContent = templateContent.replace('__SETUP_REPLACE_ID__', agentId)
  fs.writeFileSync(outputPath, finalContent, 'utf8')

  // 4. Delete temp file
  fs.unlinkSync(tempPath)

  // 5. Deploy and capture URL
  console.log(`Deploying ${output}...`)
  const deployOutput = execSync(`npx th deploy ${output}`, {
    encoding: 'utf8',
    cwd: PROJECT_ROOT,
  })
  const urls = deployOutput.match(URL_REGEX)
  if (!urls || urls.length === 0) {
    throw new Error(`Could not parse URL from deploy output for ${output}`)
  }

  return urls[urls.length - 1]
}

function main() {
  console.log('\nSetting up agents under your Toolhouse account...\n')
  console.log('This will: 1) Create 3 new agents, 2) Deploy them, 3) Create app/.env\n')

  const urls = []
  for (const agent of AGENTS) {
    const url = createAgentAndDeploy(agent)
    urls.push(url)
    console.log(`  → ${url}\n`)
  }

  const [orchestrator, debater, synthesizer] = urls

  const content = `# Toolhouse agent URLs (generated by npm run setup:env)

VITE_ORCHESTRATOR_URL=${orchestrator}
VITE_DEBATER_URL=${debater}
VITE_SYNTHESIZER_URL=${synthesizer}
`

  fs.mkdirSync(APP_DIR, { recursive: true })
  fs.writeFileSync(ENV_PATH, content, 'utf8')
  fs.writeFileSync(ENV_EXAMPLE_PATH, content, 'utf8')

  console.log(`Created ${path.relative(process.cwd(), ENV_PATH)}`)
  console.log(`Created ${path.relative(process.cwd(), ENV_EXAMPLE_PATH)}`)
  console.log('\nRun the app: npm run dev\n')
}

try {
  main()
} catch (err) {
  console.error(err.message || err)
  process.exit(1)
}
