#!/usr/bin/env node
/**
 * Deploys all Toolhouse agents, captures their URLs, and creates app/.env.
 * Run: npm run setup:env
 *
 * Requires: TOOLHOUSE_API_KEY in ~/.toolhouse or env (run `npx th login` if needed)
 */

const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

const PROJECT_ROOT = path.join(__dirname, '..')
const APP_DIR = path.join(PROJECT_ROOT, 'app')
const ENV_PATH = path.join(APP_DIR, '.env')
const ENV_EXAMPLE_PATH = path.join(APP_DIR, '.env.example')

const AGENT_FILES = ['orchestrator.yaml', 'debater.yaml', 'synthesizer.yaml']
const URL_REGEX = /https:\/\/agents\.toolhouse\.ai\/[a-zA-Z0-9-]+/g

function deployAndExtractUrl(agentFile) {
  console.log(`Deploying ${agentFile}...`)
  const output = execSync(`npx th deploy ${agentFile}`, {
    encoding: 'utf8',
    cwd: PROJECT_ROOT,
  })
  const urls = output.match(URL_REGEX)
  if (!urls || urls.length === 0) {
    throw new Error(`Could not parse URL from deploy output for ${agentFile}`)
  }
  return urls[urls.length - 1]
}

function main() {
  console.log('\nDeploying agents and creating app/.env\n')

  const urls = []
  for (const file of AGENT_FILES) {
    const url = deployAndExtractUrl(file)
    urls.push(url)
    console.log(`  → ${url}\n`)
  }

  const [orchestrator, debater, synthesizer] = urls

  const content = `# Toolhouse agent URLs (generated by npm run setup:env)

VITE_ORCHESTRATOR_URL=${orchestrator}
VITE_DEBATER_URL=${debater}
VITE_SYNTHESIZER_URL=${synthesizer}
`

  fs.mkdirSync(APP_DIR, { recursive: true })
  fs.writeFileSync(ENV_PATH, content, 'utf8')
  fs.writeFileSync(ENV_EXAMPLE_PATH, content, 'utf8')

  console.log(`Created ${path.relative(process.cwd(), ENV_PATH)}`)
  console.log(`Created ${path.relative(process.cwd(), ENV_EXAMPLE_PATH)}`)
  console.log('\nRun the app: npm run dev\n')
}

try {
  main()
} catch (err) {
  console.error(err.message || err)
  process.exit(1)
}
